"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _AssetClass:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AssetClassEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AssetClass.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ASSET_CLASS_UNSPECIFIED: _AssetClass.ValueType  # 0
    ASSET_CLASS_FX: _AssetClass.ValueType  # 1
    ASSET_CLASS_EQUITY: _AssetClass.ValueType  # 2
    ASSET_CLASS_COMMODITY: _AssetClass.ValueType  # 3
    ASSET_CLASS_DEBT: _AssetClass.ValueType  # 4
    ASSET_CLASS_INDEX: _AssetClass.ValueType  # 5
    ASSET_CLASS_CRYPTOCURRENCY: _AssetClass.ValueType  # 6
    ASSET_CLASS_ALTERNATIVE: _AssetClass.ValueType  # 7

class AssetClass(_AssetClass, metaclass=_AssetClassEnumTypeWrapper):
    """Nautilus's asset classes."""

ASSET_CLASS_UNSPECIFIED: AssetClass.ValueType  # 0
ASSET_CLASS_FX: AssetClass.ValueType  # 1
ASSET_CLASS_EQUITY: AssetClass.ValueType  # 2
ASSET_CLASS_COMMODITY: AssetClass.ValueType  # 3
ASSET_CLASS_DEBT: AssetClass.ValueType  # 4
ASSET_CLASS_INDEX: AssetClass.ValueType  # 5
ASSET_CLASS_CRYPTOCURRENCY: AssetClass.ValueType  # 6
ASSET_CLASS_ALTERNATIVE: AssetClass.ValueType  # 7
Global___AssetClass: _TypeAlias = AssetClass  # noqa: Y015

class _InstrumentClass:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _InstrumentClassEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_InstrumentClass.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    INSTRUMENT_CLASS_UNSPECIFIED: _InstrumentClass.ValueType  # 0
    INSTRUMENT_CLASS_SPOT: _InstrumentClass.ValueType  # 1
    INSTRUMENT_CLASS_SWAP: _InstrumentClass.ValueType  # 2
    INSTRUMENT_CLASS_FUTURE: _InstrumentClass.ValueType  # 3
    INSTRUMENT_CLASS_FUTURES_SPREAD: _InstrumentClass.ValueType  # 4
    INSTRUMENT_CLASS_FORWARD: _InstrumentClass.ValueType  # 5
    INSTRUMENT_CLASS_CFD: _InstrumentClass.ValueType  # 6
    INSTRUMENT_CLASS_BOND: _InstrumentClass.ValueType  # 7
    INSTRUMENT_CLASS_OPTION: _InstrumentClass.ValueType  # 8
    INSTRUMENT_CLASS_OPTION_SPREAD: _InstrumentClass.ValueType  # 9
    INSTRUMENT_CLASS_WARRANT: _InstrumentClass.ValueType  # 10
    INSTRUMENT_CLASS_SPORTS_BETTING: _InstrumentClass.ValueType  # 11
    INSTRUMENT_CLASS_BINARY_OPTION: _InstrumentClass.ValueType  # 12

class InstrumentClass(_InstrumentClass, metaclass=_InstrumentClassEnumTypeWrapper):
    """Nautilus's instrument classes."""

INSTRUMENT_CLASS_UNSPECIFIED: InstrumentClass.ValueType  # 0
INSTRUMENT_CLASS_SPOT: InstrumentClass.ValueType  # 1
INSTRUMENT_CLASS_SWAP: InstrumentClass.ValueType  # 2
INSTRUMENT_CLASS_FUTURE: InstrumentClass.ValueType  # 3
INSTRUMENT_CLASS_FUTURES_SPREAD: InstrumentClass.ValueType  # 4
INSTRUMENT_CLASS_FORWARD: InstrumentClass.ValueType  # 5
INSTRUMENT_CLASS_CFD: InstrumentClass.ValueType  # 6
INSTRUMENT_CLASS_BOND: InstrumentClass.ValueType  # 7
INSTRUMENT_CLASS_OPTION: InstrumentClass.ValueType  # 8
INSTRUMENT_CLASS_OPTION_SPREAD: InstrumentClass.ValueType  # 9
INSTRUMENT_CLASS_WARRANT: InstrumentClass.ValueType  # 10
INSTRUMENT_CLASS_SPORTS_BETTING: InstrumentClass.ValueType  # 11
INSTRUMENT_CLASS_BINARY_OPTION: InstrumentClass.ValueType  # 12
Global___InstrumentClass: _TypeAlias = InstrumentClass  # noqa: Y015

class _ModelArgument:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ModelArgumentEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ModelArgument.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    MODEL_ARGUMENT_UNSPECIFIED: _ModelArgument.ValueType  # 0
    MODEL_ARGUMENT_FEE_MODEL: _ModelArgument.ValueType  # 1
    MODEL_ARGUMENT_FILL_MODEL: _ModelArgument.ValueType  # 2
    MODEL_ARGUMENT_LATENCY_MODEL: _ModelArgument.ValueType  # 3
    MODEL_ARGUMENT_MARGIN_MODEL: _ModelArgument.ValueType  # 4
    MODEL_ARGUMENT_MODULES: _ModelArgument.ValueType  # 5

class ModelArgument(_ModelArgument, metaclass=_ModelArgumentEnumTypeWrapper): ...

MODEL_ARGUMENT_UNSPECIFIED: ModelArgument.ValueType  # 0
MODEL_ARGUMENT_FEE_MODEL: ModelArgument.ValueType  # 1
MODEL_ARGUMENT_FILL_MODEL: ModelArgument.ValueType  # 2
MODEL_ARGUMENT_LATENCY_MODEL: ModelArgument.ValueType  # 3
MODEL_ARGUMENT_MARGIN_MODEL: ModelArgument.ValueType  # 4
MODEL_ARGUMENT_MODULES: ModelArgument.ValueType  # 5
Global___ModelArgument: _TypeAlias = ModelArgument  # noqa: Y015

class _ParameterType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ParameterTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ParameterType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PARAMETER_TYPE_UNSPECIFIED: _ParameterType.ValueType  # 0
    PARAMETER_TYPE_STRING: _ParameterType.ValueType  # 1
    """Also a parameter whose type the server cannot tell."""
    PARAMETER_TYPE_INTEGER: _ParameterType.ValueType  # 2
    PARAMETER_TYPE_NUMBER: _ParameterType.ValueType  # 3
    PARAMETER_TYPE_BOOLEAN: _ParameterType.ValueType  # 4

class ParameterType(_ParameterType, metaclass=_ParameterTypeEnumTypeWrapper): ...

PARAMETER_TYPE_UNSPECIFIED: ParameterType.ValueType  # 0
PARAMETER_TYPE_STRING: ParameterType.ValueType  # 1
"""Also a parameter whose type the server cannot tell."""
PARAMETER_TYPE_INTEGER: ParameterType.ValueType  # 2
PARAMETER_TYPE_NUMBER: ParameterType.ValueType  # 3
PARAMETER_TYPE_BOOLEAN: ParameterType.ValueType  # 4
Global___ParameterType: _TypeAlias = ParameterType  # noqa: Y015

@_typing.final
class VenueModel(_message.Message):
    """A model argument of a venue; ListModelKinds gives the kinds of each."""

    DESCRIPTOR: _descriptor.Descriptor

    KIND_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    kind: _builtins.str
    @_builtins.property
    def config(self) -> _struct_pb2.Struct:
        """Absent stores no config table; an integral number is stored as an integer."""

    def __init__(
        self,
        *,
        kind: _builtins.str = ...,
        config: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "kind", b"kind"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VenueModel: _TypeAlias = VenueModel  # noqa: Y015

@_typing.final
class VenueProfile(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    VENUE_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    ASSET_CLASS_FIELD_NUMBER: _builtins.int
    INSTRUMENT_CLASS_FIELD_NUMBER: _builtins.int
    FEE_MODEL_FIELD_NUMBER: _builtins.int
    FILL_MODEL_FIELD_NUMBER: _builtins.int
    LATENCY_MODEL_FIELD_NUMBER: _builtins.int
    MARGIN_MODEL_FIELD_NUMBER: _builtins.int
    MODULES_FIELD_NUMBER: _builtins.int
    ARGUMENTS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The profile's name, which a spec's `venue` selects."""
    venue: _builtins.str
    """The nautilus venue's name, such as BYBIT."""
    source: _builtins.str
    """The data source the venue's data comes from, such as bybit."""
    asset_class: Global___AssetClass.ValueType
    instrument_class: Global___InstrumentClass.ValueType
    @_builtins.property
    def fee_model(self) -> Global___VenueModel: ...
    @_builtins.property
    def fill_model(self) -> Global___VenueModel: ...
    @_builtins.property
    def latency_model(self) -> Global___VenueModel: ...
    @_builtins.property
    def margin_model(self) -> Global___VenueModel: ...
    @_builtins.property
    def modules(self) -> _containers.RepeatedCompositeFieldContainer[Global___VenueModel]: ...
    @_builtins.property
    def arguments(self) -> _struct_pb2.Struct:
        """The other BacktestVenueConfig arguments; an integral number is stored as an integer."""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        venue: _builtins.str = ...,
        source: _builtins.str = ...,
        asset_class: Global___AssetClass.ValueType = ...,
        instrument_class: Global___InstrumentClass.ValueType = ...,
        fee_model: Global___VenueModel | None = ...,
        fill_model: Global___VenueModel | None = ...,
        latency_model: Global___VenueModel | None = ...,
        margin_model: Global___VenueModel | None = ...,
        modules: _abc.Iterable[Global___VenueModel] | None = ...,
        arguments: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["arguments", b"arguments", "fee_model", b"fee_model", "fill_model", b"fill_model", "latency_model", b"latency_model", "margin_model", b"margin_model"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arguments", b"arguments", "asset_class", b"asset_class", "fee_model", b"fee_model", "fill_model", b"fill_model", "instrument_class", b"instrument_class", "latency_model", b"latency_model", "margin_model", b"margin_model", "modules", b"modules", "name", b"name", "source", b"source", "venue", b"venue"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VenueProfile: _TypeAlias = VenueProfile  # noqa: Y015

@_typing.final
class ListVenueProfiles(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListVenueProfiles: _TypeAlias = ListVenueProfiles  # noqa: Y015

@_typing.final
class VenueProfiles(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROFILES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def profiles(self) -> _containers.RepeatedCompositeFieldContainer[Global___VenueProfile]: ...
    def __init__(
        self,
        *,
        profiles: _abc.Iterable[Global___VenueProfile] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["profiles", b"profiles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VenueProfiles: _TypeAlias = VenueProfiles  # noqa: Y015

@_typing.final
class PutVenueProfile(_message.Message):
    """Creates the profile, or replaces the one of the same name."""

    DESCRIPTOR: _descriptor.Descriptor

    PROFILE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def profile(self) -> Global___VenueProfile: ...
    def __init__(
        self,
        *,
        profile: Global___VenueProfile | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["profile", b"profile"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["profile", b"profile"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PutVenueProfile: _TypeAlias = PutVenueProfile  # noqa: Y015

@_typing.final
class DeleteVenueProfile(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteVenueProfile: _TypeAlias = DeleteVenueProfile  # noqa: Y015

@_typing.final
class ConfigWritten(_message.Message):
    """The answer to a write that succeeded."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConfigWritten: _TypeAlias = ConfigWritten  # noqa: Y015

@_typing.final
class KnownGap(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_FIELD_NUMBER: _builtins.int
    SYMBOL_FIELD_NUMBER: _builtins.int
    DATA_TYPE_FIELD_NUMBER: _builtins.int
    DAY_FIELD_NUMBER: _builtins.int
    source: _builtins.str
    symbol: _builtins.str
    data_type: _builtins.str
    """The data type as the source's list names it, such as trades."""
    day: _builtins.str
    """An ISO 8601 date, YYYY-MM-DD, in UTC."""
    def __init__(
        self,
        *,
        source: _builtins.str = ...,
        symbol: _builtins.str = ...,
        data_type: _builtins.str = ...,
        day: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_type", b"data_type", "day", b"day", "source", b"source", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___KnownGap: _TypeAlias = KnownGap  # noqa: Y015

@_typing.final
class ListKnownGaps(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListKnownGaps: _TypeAlias = ListKnownGaps  # noqa: Y015

@_typing.final
class KnownGaps(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GAPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def gaps(self) -> _containers.RepeatedCompositeFieldContainer[Global___KnownGap]: ...
    def __init__(
        self,
        *,
        gaps: _abc.Iterable[Global___KnownGap] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gaps", b"gaps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___KnownGaps: _TypeAlias = KnownGaps  # noqa: Y015

@_typing.final
class AddKnownGaps(_message.Message):
    """Adds the gaps not listed yet; all of them or none."""

    DESCRIPTOR: _descriptor.Descriptor

    GAPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def gaps(self) -> _containers.RepeatedCompositeFieldContainer[Global___KnownGap]: ...
    def __init__(
        self,
        *,
        gaps: _abc.Iterable[Global___KnownGap] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gaps", b"gaps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddKnownGaps: _TypeAlias = AddKnownGaps  # noqa: Y015

@_typing.final
class RemoveKnownGaps(_message.Message):
    """Removes the gaps listed; gaps not listed are skipped."""

    DESCRIPTOR: _descriptor.Descriptor

    GAPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def gaps(self) -> _containers.RepeatedCompositeFieldContainer[Global___KnownGap]: ...
    def __init__(
        self,
        *,
        gaps: _abc.Iterable[Global___KnownGap] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gaps", b"gaps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveKnownGaps: _TypeAlias = RemoveKnownGaps  # noqa: Y015

@_typing.final
class ModelParameter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    REQUIRED_FIELD_NUMBER: _builtins.int
    DEFAULT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    type: Global___ParameterType.ValueType
    required: _builtins.bool
    @_builtins.property
    def default(self) -> _struct_pb2.Value:
        """Absent when the parameter has no default."""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        type: Global___ParameterType.ValueType = ...,
        required: _builtins.bool = ...,
        default: _struct_pb2.Value | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["default", b"default"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["default", b"default", "name", b"name", "required", b"required", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelParameter: _TypeAlias = ModelParameter  # noqa: Y015

@_typing.final
class ModelKind(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def parameters(self) -> _containers.RepeatedCompositeFieldContainer[Global___ModelParameter]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        parameters: _abc.Iterable[Global___ModelParameter] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "parameters", b"parameters"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelKind: _TypeAlias = ModelKind  # noqa: Y015

@_typing.final
class ModelArgumentKinds(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ARGUMENT_FIELD_NUMBER: _builtins.int
    KINDS_FIELD_NUMBER: _builtins.int
    argument: Global___ModelArgument.ValueType
    @_builtins.property
    def kinds(self) -> _containers.RepeatedCompositeFieldContainer[Global___ModelKind]:
        """Empty when the argument has no kind yet."""

    def __init__(
        self,
        *,
        argument: Global___ModelArgument.ValueType = ...,
        kinds: _abc.Iterable[Global___ModelKind] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["argument", b"argument", "kinds", b"kinds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelArgumentKinds: _TypeAlias = ModelArgumentKinds  # noqa: Y015

@_typing.final
class ListModelKinds(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListModelKinds: _TypeAlias = ListModelKinds  # noqa: Y015

@_typing.final
class ModelKinds(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ARGUMENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def arguments(self) -> _containers.RepeatedCompositeFieldContainer[Global___ModelArgumentKinds]: ...
    def __init__(
        self,
        *,
        arguments: _abc.Iterable[Global___ModelArgumentKinds] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arguments", b"arguments"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelKinds: _TypeAlias = ModelKinds  # noqa: Y015
