"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from sbt2.protocol.v1 import config_pb2 as _config_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _JobState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _JobStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_JobState.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    JOB_STATE_UNSPECIFIED: _JobState.ValueType  # 0
    JOB_STATE_QUEUED: _JobState.ValueType  # 1
    """Checked, and waiting for the jobs before it."""
    JOB_STATE_CHECKING: _JobState.ValueType  # 2
    JOB_STATE_RUNNING: _JobState.ValueType  # 3
    JOB_STATE_FINISHED: _JobState.ValueType  # 4
    JOB_STATE_FAILED: _JobState.ValueType  # 5
    JOB_STATE_CANCELLED: _JobState.ValueType  # 6

class JobState(_JobState, metaclass=_JobStateEnumTypeWrapper): ...

JOB_STATE_UNSPECIFIED: JobState.ValueType  # 0
JOB_STATE_QUEUED: JobState.ValueType  # 1
"""Checked, and waiting for the jobs before it."""
JOB_STATE_CHECKING: JobState.ValueType  # 2
JOB_STATE_RUNNING: JobState.ValueType  # 3
JOB_STATE_FINISHED: JobState.ValueType  # 4
JOB_STATE_FAILED: JobState.ValueType  # 5
JOB_STATE_CANCELLED: JobState.ValueType  # 6
Global___JobState: _TypeAlias = JobState  # noqa: Y015

class _RunStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RunStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RunStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RUN_STATUS_UNSPECIFIED: _RunStatus.ValueType  # 0
    RUN_STATUS_PENDING: _RunStatus.ValueType  # 1
    RUN_STATUS_RUNNING: _RunStatus.ValueType  # 2
    RUN_STATUS_FINISHED: _RunStatus.ValueType  # 3
    RUN_STATUS_FAILED: _RunStatus.ValueType  # 4
    RUN_STATUS_CANCELLED: _RunStatus.ValueType  # 5

class RunStatus(_RunStatus, metaclass=_RunStatusEnumTypeWrapper): ...

RUN_STATUS_UNSPECIFIED: RunStatus.ValueType  # 0
RUN_STATUS_PENDING: RunStatus.ValueType  # 1
RUN_STATUS_RUNNING: RunStatus.ValueType  # 2
RUN_STATUS_FINISHED: RunStatus.ValueType  # 3
RUN_STATUS_FAILED: RunStatus.ValueType  # 4
RUN_STATUS_CANCELLED: RunStatus.ValueType  # 5
Global___RunStatus: _TypeAlias = RunStatus  # noqa: Y015

@_typing.final
class SpecPeriod(_message.Message):
    """The period a spec covers, before its split."""

    DESCRIPTOR: _descriptor.Descriptor

    START_AT_FIELD_NUMBER: _builtins.int
    END_AT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def start_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def end_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        start_at: _timestamp_pb2.Timestamp | None = ...,
        end_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["end_at", b"end_at", "start_at", b"start_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_at", b"end_at", "start_at", b"start_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpecPeriod: _TypeAlias = SpecPeriod  # noqa: Y015

@_typing.final
class SpecFile(_message.Message):
    """A spec file's table, key for key."""

    DESCRIPTOR: _descriptor.Descriptor

    STRATEGY_FIELD_NUMBER: _builtins.int
    INSTRUMENTS_FIELD_NUMBER: _builtins.int
    PERIOD_FIELD_NUMBER: _builtins.int
    VENUE_FIELD_NUMBER: _builtins.int
    CAPITAL_FIELD_NUMBER: _builtins.int
    PART_FIELD_NUMBER: _builtins.int
    SPLIT_FIELD_NUMBER: _builtins.int
    SEED_FIELD_NUMBER: _builtins.int
    EQUITY_INTERVAL_FIELD_NUMBER: _builtins.int
    LIQUIDATION_FIELD_NUMBER: _builtins.int
    BARS_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    RISK_FIELD_NUMBER: _builtins.int
    STUDY_FIELD_NUMBER: _builtins.int
    strategy: _builtins.str
    """The strategy's class in the uploaded module, as "module:Class"."""
    venue: _builtins.str
    """The name of a venue profile in the server's config."""
    capital: _builtins.str
    """A nautilus money string, such as "10000 USDT"."""
    seed: _builtins.int
    equity_interval: _builtins.str
    liquidation: _builtins.bool
    bars: _builtins.str
    study: _builtins.str
    @_builtins.property
    def instruments(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def period(self) -> Global___SpecPeriod: ...
    @_builtins.property
    def part(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The parts to run: train, validation or test. Empty runs train and validation."""

    @_builtins.property
    def split(self) -> _struct_pb2.Struct:
        """The split's table: validation_start and test_start as ISO 8601 strings, or
        validation and test as fractions.
        """

    @_builtins.property
    def params(self) -> _struct_pb2.Struct:
        """The strategy's parameters; a list value is a sweep, one run for each of its
        items. An integral number is read as an integer.
        """

    @_builtins.property
    def risk(self) -> _struct_pb2.Struct:
        """The risk table: drawdown_limit and the risk engine's limits."""

    def __init__(
        self,
        *,
        strategy: _builtins.str = ...,
        instruments: _abc.Iterable[_builtins.str] | None = ...,
        period: Global___SpecPeriod | None = ...,
        venue: _builtins.str = ...,
        capital: _builtins.str = ...,
        part: _abc.Iterable[_builtins.str] | None = ...,
        split: _struct_pb2.Struct | None = ...,
        seed: _builtins.int | None = ...,
        equity_interval: _builtins.str | None = ...,
        liquidation: _builtins.bool | None = ...,
        bars: _builtins.str | None = ...,
        params: _struct_pb2.Struct | None = ...,
        risk: _struct_pb2.Struct | None = ...,
        study: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bars", b"_bars", "_equity_interval", b"_equity_interval", "_liquidation", b"_liquidation", "_seed", b"_seed", "_study", b"_study", "bars", b"bars", "equity_interval", b"equity_interval", "liquidation", b"liquidation", "params", b"params", "period", b"period", "risk", b"risk", "seed", b"seed", "split", b"split", "study", b"study"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bars", b"_bars", "_equity_interval", b"_equity_interval", "_liquidation", b"_liquidation", "_seed", b"_seed", "_study", b"_study", "bars", b"bars", "capital", b"capital", "equity_interval", b"equity_interval", "instruments", b"instruments", "liquidation", b"liquidation", "params", b"params", "part", b"part", "period", b"period", "risk", b"risk", "seed", b"seed", "split", b"split", "strategy", b"strategy", "study", b"study", "venue", b"venue"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bars: _TypeAlias = _typing.Literal["bars"]  # noqa: Y015
    _WhichOneofArgType__bars: _TypeAlias = _typing.Literal["_bars", b"_bars"]  # noqa: Y015
    _WhichOneofReturnType__equity_interval: _TypeAlias = _typing.Literal["equity_interval"]  # noqa: Y015
    _WhichOneofArgType__equity_interval: _TypeAlias = _typing.Literal["_equity_interval", b"_equity_interval"]  # noqa: Y015
    _WhichOneofReturnType__liquidation: _TypeAlias = _typing.Literal["liquidation"]  # noqa: Y015
    _WhichOneofArgType__liquidation: _TypeAlias = _typing.Literal["_liquidation", b"_liquidation"]  # noqa: Y015
    _WhichOneofReturnType__seed: _TypeAlias = _typing.Literal["seed"]  # noqa: Y015
    _WhichOneofArgType__seed: _TypeAlias = _typing.Literal["_seed", b"_seed"]  # noqa: Y015
    _WhichOneofReturnType__study: _TypeAlias = _typing.Literal["study"]  # noqa: Y015
    _WhichOneofArgType__study: _TypeAlias = _typing.Literal["_study", b"_study"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bars) -> _WhichOneofReturnType__bars | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__equity_interval) -> _WhichOneofReturnType__equity_interval | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__liquidation) -> _WhichOneofReturnType__liquidation | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__seed) -> _WhichOneofReturnType__seed | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__study) -> _WhichOneofReturnType__study | None: ...

Global___SpecFile: _TypeAlias = SpecFile  # noqa: Y015

@_typing.final
class StrategyModule(_message.Message):
    """A single-module strategy, sent as source."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """A Python identifier that no module of the server's image already has."""
    source: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        source: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "source", b"source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StrategyModule: _TypeAlias = StrategyModule  # noqa: Y015

@_typing.final
class SubmitRun(_message.Message):
    """Starts a job whose runs are the spec's expansion. The server answers once the
    spec is checked: JobSubmitted, or an Error and no job.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SPEC_FIELD_NUMBER: _builtins.int
    STRATEGY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def spec(self) -> Global___SpecFile: ...
    @_builtins.property
    def strategy(self) -> Global___StrategyModule: ...
    def __init__(
        self,
        *,
        spec: Global___SpecFile | None = ...,
        strategy: Global___StrategyModule | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["spec", b"spec", "strategy", b"strategy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["spec", b"spec", "strategy", b"strategy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitRun: _TypeAlias = SubmitRun  # noqa: Y015

@_typing.final
class JobSubmitted(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    RUN_IDS_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    @_builtins.property
    def run_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The runs the job makes, in the order the spec expands into them."""

    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        run_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id", "run_ids", b"run_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JobSubmitted: _TypeAlias = JobSubmitted  # noqa: Y015

@_typing.final
class RunState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    state: Global___RunStatus.ValueType
    reason: _builtins.str
    """Why the run failed; empty otherwise."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        state: Global___RunStatus.ValueType = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason", "run_id", b"run_id", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RunState: _TypeAlias = RunState  # noqa: Y015

@_typing.final
class Job(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    RUNS_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    state: Global___JobState.ValueType
    reason: _builtins.str
    """Why a failed job failed when no run is to blame; empty otherwise."""
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___RunState]: ...
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        state: Global___JobState.ValueType = ...,
        runs: _abc.Iterable[Global___RunState] | None = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id", "reason", b"reason", "runs", b"runs", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Job: _TypeAlias = Job  # noqa: Y015

@_typing.final
class CancelJob(_message.Message):
    """Stops the job; its runs not finished become cancelled. Cancelling a finished
    job does nothing.
    """

    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelJob: _TypeAlias = CancelJob  # noqa: Y015

@_typing.final
class JobCancelled(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JobCancelled: _TypeAlias = JobCancelled  # noqa: Y015

@_typing.final
class ListJobs(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListJobs: _TypeAlias = ListJobs  # noqa: Y015

@_typing.final
class Jobs(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOBS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def jobs(self) -> _containers.RepeatedCompositeFieldContainer[Global___Job]: ...
    def __init__(
        self,
        *,
        jobs: _abc.Iterable[Global___Job] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["jobs", b"jobs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Jobs: _TypeAlias = Jobs  # noqa: Y015

@_typing.final
class SubscribeJob(_message.Message):
    """Follows a job: JobSubscribed first, then a JobUpdate push for each change,
    at most a few a second, the last one when the job is over.
    """

    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubscribeJob: _TypeAlias = SubscribeJob  # noqa: Y015

@_typing.final
class JobSubscribed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBSCRIPTION_ID_FIELD_NUMBER: _builtins.int
    JOB_FIELD_NUMBER: _builtins.int
    LOG_LINES_FIELD_NUMBER: _builtins.int
    subscription_id: _builtins.int
    """Names the subscription in the pushes that follow, and in Unsubscribe."""
    @_builtins.property
    def job(self) -> Global___Job: ...
    @_builtins.property
    def log_lines(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The latest lines the job printed, oldest first."""

    def __init__(
        self,
        *,
        subscription_id: _builtins.int = ...,
        job: Global___Job | None = ...,
        log_lines: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["job", b"job"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job", b"job", "log_lines", b"log_lines", "subscription_id", b"subscription_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JobSubscribed: _TypeAlias = JobSubscribed  # noqa: Y015

@_typing.final
class JobUpdate(_message.Message):
    """A push of a subscription, with the run states that changed."""

    DESCRIPTOR: _descriptor.Descriptor

    RUNS_FIELD_NUMBER: _builtins.int
    LOG_LINES_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    state: Global___JobState.ValueType
    reason: _builtins.str
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___RunState]: ...
    @_builtins.property
    def log_lines(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Lines of the job's stdout and stderr, in the order they were printed."""

    def __init__(
        self,
        *,
        runs: _abc.Iterable[Global___RunState] | None = ...,
        log_lines: _abc.Iterable[_builtins.str] | None = ...,
        state: Global___JobState.ValueType = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["log_lines", b"log_lines", "reason", b"reason", "runs", b"runs", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JobUpdate: _TypeAlias = JobUpdate  # noqa: Y015

@_typing.final
class Unsubscribe(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBSCRIPTION_ID_FIELD_NUMBER: _builtins.int
    subscription_id: _builtins.int
    def __init__(
        self,
        *,
        subscription_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["subscription_id", b"subscription_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Unsubscribe: _TypeAlias = Unsubscribe  # noqa: Y015

@_typing.final
class Unsubscribed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Unsubscribed: _TypeAlias = Unsubscribed  # noqa: Y015

@_typing.final
class DescribeStrategy(_message.Message):
    """Asks for the parameter schema of a strategy module. The server imports the
    module in a process of its own, never in its own. A module with no strategy
    or more than one, one that fails to import or takes too long to, one with a
    parameter of an unsupported type, or a name the image already has, answers
    INVALID_ARGUMENT.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STRATEGY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def strategy(self) -> Global___StrategyModule: ...
    def __init__(
        self,
        *,
        strategy: Global___StrategyModule | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["strategy", b"strategy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DescribeStrategy: _TypeAlias = DescribeStrategy  # noqa: Y015

@_typing.final
class StrategyParameter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    REQUIRED_FIELD_NUMBER: _builtins.int
    DEFAULT_FIELD_NUMBER: _builtins.int
    CHOICES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    type: _config_pb2.ParameterType.ValueType
    required: _builtins.bool
    @_builtins.property
    def default(self) -> _struct_pb2.Value:
        """Absent when the parameter is required. A decimal is a string."""

    @_builtins.property
    def choices(self) -> _containers.RepeatedCompositeFieldContainer[_struct_pb2.Value]:
        """The allowed values when the parameter is a Literal; empty otherwise."""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        type: _config_pb2.ParameterType.ValueType = ...,
        required: _builtins.bool = ...,
        default: _struct_pb2.Value | None = ...,
        choices: _abc.Iterable[_struct_pb2.Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["default", b"default"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["choices", b"choices", "default", b"default", "name", b"name", "required", b"required", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StrategyParameter: _TypeAlias = StrategyParameter  # noqa: Y015

@_typing.final
class StrategySchema(_message.Message):
    """The strategy a module defines: the concrete Strategy subclasses whose module
    is that one. Imported ones do not count.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STRATEGY_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    PARAMS_DESCRIPTION_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    strategy: _builtins.str
    """The strategy's class, as "module:Class"."""
    description: _builtins.str
    """The strategy's docstring; empty when it has none."""
    params_description: _builtins.str
    """The docstring of its Params; empty when it has none."""
    @_builtins.property
    def parameters(self) -> _containers.RepeatedCompositeFieldContainer[Global___StrategyParameter]: ...
    def __init__(
        self,
        *,
        strategy: _builtins.str = ...,
        description: _builtins.str = ...,
        params_description: _builtins.str = ...,
        parameters: _abc.Iterable[Global___StrategyParameter] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "parameters", b"parameters", "params_description", b"params_description", "strategy", b"strategy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StrategySchema: _TypeAlias = StrategySchema  # noqa: Y015
