"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ErrorCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ErrorCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ERROR_CODE_UNSPECIFIED: _ErrorCode.ValueType  # 0
    ERROR_CODE_INVALID_MESSAGE: _ErrorCode.ValueType  # 1
    """The frame is not a ClientMessage, or its body is unset."""
    ERROR_CODE_INVALID_ARGUMENT: _ErrorCode.ValueType  # 2
    ERROR_CODE_NOT_FOUND: _ErrorCode.ValueType  # 3
    ERROR_CODE_UNIMPLEMENTED: _ErrorCode.ValueType  # 4
    """The server does not handle this body."""
    ERROR_CODE_UNSUPPORTED_VERSION: _ErrorCode.ValueType  # 5
    ERROR_CODE_INTERNAL: _ErrorCode.ValueType  # 6
    ERROR_CODE_RESOURCE_EXHAUSTED: _ErrorCode.ValueType  # 7
    """One indivisible response record exceeds the maximum envelope size."""

class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper): ...

ERROR_CODE_UNSPECIFIED: ErrorCode.ValueType  # 0
ERROR_CODE_INVALID_MESSAGE: ErrorCode.ValueType  # 1
"""The frame is not a ClientMessage, or its body is unset."""
ERROR_CODE_INVALID_ARGUMENT: ErrorCode.ValueType  # 2
ERROR_CODE_NOT_FOUND: ErrorCode.ValueType  # 3
ERROR_CODE_UNIMPLEMENTED: ErrorCode.ValueType  # 4
"""The server does not handle this body."""
ERROR_CODE_UNSUPPORTED_VERSION: ErrorCode.ValueType  # 5
ERROR_CODE_INTERNAL: ErrorCode.ValueType  # 6
ERROR_CODE_RESOURCE_EXHAUSTED: ErrorCode.ValueType  # 7
"""One indivisible response record exceeds the maximum envelope size."""
Global___ErrorCode: _TypeAlias = ErrorCode  # noqa: Y015

@_typing.final
class Error(_message.Message):
    """Lives here rather than in envelope.proto so that area files can embed it without an import cycle."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DetailsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    DETAILS_FIELD_NUMBER: _builtins.int
    code: Global___ErrorCode.ValueType
    message: _builtins.str
    @_builtins.property
    def details(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        code: Global___ErrorCode.ValueType = ...,
        message: _builtins.str = ...,
        details: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "details", b"details", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Error: _TypeAlias = Error  # noqa: Y015
