default_install_hook_types: [pre-commit, commit-msg, post-merge]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run --locked pyright
        language: system
        types: [python]
        pass_filenames: false

      - id: prune-merged-branches
        name: prune merged branches
        entry: scripts/prune-merged-branches.sh
        language: script
        stages: [post-merge]
        always_run: true
        pass_filenames: false
        verbose: true
