[package]
name = "sbt2-gui"
description = "The sbt2 GUI"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sbt2-client = { path = "../sbt2-client" }
iced = { version = "=0.14.0", features = ["tokio"] }
keyring-core = "1"
zbus-secret-service-keyring-store = { version = "1", features = ["crypto-rust"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9"
tokio = { version = "1", features = ["rt", "sync"] }
iced_plot = { version = "=0.5.0", features = ["canvas"] }

[dev-dependencies]
sbt2-client = { path = "../sbt2-client", features = ["test-support"] }
iced_test = "=0.14.0"
tempfile = "3"
