[package]
name = "sbt2-gui"
description = "The sbt2 GUI"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sbt2-client = { path = "../sbt2-client" }
iced = { version = "=0.14.0", features = ["tokio"] }
directories = "6"
keyring-core = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
tokio = { version = "1", features = ["rt", "sync"] }
iced_plot = { version = "=0.5.0", features = ["canvas"] }
iced_aw = { version = "=0.14.1", default-features = false, features = ["card", "badge", "spinner"] }

[target.'cfg(target_os = "linux")'.dependencies]
zbus-secret-service-keyring-store = { version = "1", features = ["crypto-rust"] }

[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store = { version = "1", features = ["keychain"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = "1"

[dev-dependencies]
sbt2-client = { path = "../sbt2-client", features = ["test-support"] }
iced_test = "=0.14.0"
prost-types = "=0.14.4"
tempfile = "3"
