"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from sbt2.v1 import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Capability:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CapabilityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Capability.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CAPABILITY_UNSPECIFIED: _Capability.ValueType  # 0

class Capability(_Capability, metaclass=_CapabilityEnumTypeWrapper): ...

CAPABILITY_UNSPECIFIED: Capability.ValueType  # 0
Global___Capability: _TypeAlias = Capability  # noqa: Y015

@_typing.final
class ClientMessage(_message.Message):
    """Each binary WebSocket frame the client sends is one ClientMessage."""

    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    HELLO_FIELD_NUMBER: _builtins.int
    request_id: _builtins.int
    """Chosen by the client and never 0; the server's answers carry it back."""
    @_builtins.property
    def hello(self) -> Global___Hello: ...
    def __init__(
        self,
        *,
        request_id: _builtins.int = ...,
        hello: Global___Hello | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "hello", b"hello"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "hello", b"hello", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_body: _TypeAlias = _typing.Literal["hello"]  # noqa: Y015
    _WhichOneofArgType_body: _TypeAlias = _typing.Literal["body", b"body"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_body) -> _WhichOneofReturnType_body | None: ...

Global___ClientMessage: _TypeAlias = ClientMessage  # noqa: Y015

@_typing.final
class ServerMessage(_message.Message):
    """Each binary WebSocket frame the server sends is one ServerMessage."""

    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    SUBSCRIPTION_ID_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    WELCOME_FIELD_NUMBER: _builtins.int
    request_id: _builtins.int
    """0 on a push, which carries the subscription it belongs to instead."""
    subscription_id: _builtins.int
    """0 on an answer to a request."""
    @_builtins.property
    def error(self) -> _types_pb2.Error: ...
    @_builtins.property
    def welcome(self) -> Global___Welcome: ...
    def __init__(
        self,
        *,
        request_id: _builtins.int = ...,
        subscription_id: _builtins.int = ...,
        error: _types_pb2.Error | None = ...,
        welcome: Global___Welcome | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "error", b"error", "welcome", b"welcome"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "error", b"error", "request_id", b"request_id", "subscription_id", b"subscription_id", "welcome", b"welcome"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_body: _TypeAlias = _typing.Literal["error", "welcome"]  # noqa: Y015
    _WhichOneofArgType_body: _TypeAlias = _typing.Literal["body", b"body"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_body) -> _WhichOneofReturnType_body | None: ...

Global___ServerMessage: _TypeAlias = ServerMessage  # noqa: Y015

@_typing.final
class Hello(_message.Message):
    """The client's first message on a connection."""

    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_VERSION_FIELD_NUMBER: _builtins.int
    client_version: _builtins.str
    def __init__(
        self,
        *,
        client_version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_version", b"client_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Hello: _TypeAlias = Hello  # noqa: Y015

@_typing.final
class Welcome(_message.Message):
    """The answer to Hello."""

    DESCRIPTOR: _descriptor.Descriptor

    SERVER_VERSION_FIELD_NUMBER: _builtins.int
    CAPABILITIES_FIELD_NUMBER: _builtins.int
    server_version: _builtins.str
    @_builtins.property
    def capabilities(self) -> _containers.RepeatedScalarFieldContainer[Global___Capability.ValueType]: ...
    def __init__(
        self,
        *,
        server_version: _builtins.str = ...,
        capabilities: _abc.Iterable[Global___Capability.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities", "server_version", b"server_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Welcome: _TypeAlias = Welcome  # noqa: Y015
