# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sbt2/v1/envelope.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'sbt2/v1/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sbt2.v1 import types_pb2 as sbt2_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sbt2/v1/envelope.proto\x12\x07sbt2.v1\x1a\x13sbt2/v1/types.proto\"^\n\rClientMessage\x12\x1d\n\nrequest_id\x18\x01 \x01(\x04R\trequestId\x12&\n\x05hello\x18\x02 \x01(\x0b\x32\x0e.sbt2.v1.HelloH\x00R\x05helloB\x06\n\x04\x62ody\"\xb5\x01\n\rServerMessage\x12\x1d\n\nrequest_id\x18\x01 \x01(\x04R\trequestId\x12\'\n\x0fsubscription_id\x18\x02 \x01(\x04R\x0esubscriptionId\x12&\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x0e.sbt2.v1.ErrorH\x00R\x05\x65rror\x12,\n\x07welcome\x18\x04 \x01(\x0b\x32\x10.sbt2.v1.WelcomeH\x00R\x07welcomeB\x06\n\x04\x62ody\".\n\x05Hello\x12%\n\x0e\x63lient_version\x18\x01 \x01(\tR\rclientVersion\"i\n\x07Welcome\x12%\n\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12\x37\n\x0c\x63\x61pabilities\x18\x02 \x03(\x0e\x32\x13.sbt2.v1.CapabilityR\x0c\x63\x61pabilities*(\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sbt2.v1.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPABILITY']._serialized_start=491
  _globals['_CAPABILITY']._serialized_end=531
  _globals['_CLIENTMESSAGE']._serialized_start=56
  _globals['_CLIENTMESSAGE']._serialized_end=150
  _globals['_SERVERMESSAGE']._serialized_start=153
  _globals['_SERVERMESSAGE']._serialized_end=334
  _globals['_HELLO']._serialized_start=336
  _globals['_HELLO']._serialized_end=382
  _globals['_WELCOME']._serialized_start=384
  _globals['_WELCOME']._serialized_end=489
# @@protoc_insertion_point(module_scope)
