# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sbt2/protocol/v1/types.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'sbt2/protocol/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csbt2/protocol/v1/types.proto\x12\x10sbt2.protocol.v1\"\xce\x01\n\x05\x45rror\x12/\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1b.sbt2.protocol.v1.ErrorCodeR\x04\x63ode\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12>\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32$.sbt2.protocol.v1.Error.DetailsEntryR\x07\x64\x65tails\x1a:\n\x0c\x44\x65tailsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01*\xdd\x01\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n\x1a\x45RROR_CODE_INVALID_MESSAGE\x10\x01\x12\x1f\n\x1b\x45RROR_CODE_INVALID_ARGUMENT\x10\x02\x12\x18\n\x14\x45RROR_CODE_NOT_FOUND\x10\x03\x12\x1c\n\x18\x45RROR_CODE_UNIMPLEMENTED\x10\x04\x12\"\n\x1e\x45RROR_CODE_UNSUPPORTED_VERSION\x10\x05\x12\x17\n\x13\x45RROR_CODE_INTERNAL\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sbt2.protocol.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERROR_DETAILSENTRY']._loaded_options = None
  _globals['_ERROR_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_ERRORCODE']._serialized_start=260
  _globals['_ERRORCODE']._serialized_end=481
  _globals['_ERROR']._serialized_start=51
  _globals['_ERROR']._serialized_end=257
  _globals['_ERROR_DETAILSENTRY']._serialized_start=199
  _globals['_ERROR_DETAILSENTRY']._serialized_end=257
# @@protoc_insertion_point(module_scope)
