"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _StudyConflictKind:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StudyConflictKindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_StudyConflictKind.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STUDY_CONFLICT_KIND_UNSPECIFIED: _StudyConflictKind.ValueType  # 0
    STUDY_CONFLICT_KIND_CONTEXT: _StudyConflictKind.ValueType  # 1
    """The run's context differs from the study's."""
    STUDY_CONFLICT_KIND_CODE: _StudyConflictKind.ValueType  # 2
    """The strategy's source differs from the one the study pinned."""
    STUDY_CONFLICT_KIND_DUPLICATE_RUN: _StudyConflictKind.ValueType  # 3
    """The study already holds a run with the same parameters."""

class StudyConflictKind(_StudyConflictKind, metaclass=_StudyConflictKindEnumTypeWrapper): ...

STUDY_CONFLICT_KIND_UNSPECIFIED: StudyConflictKind.ValueType  # 0
STUDY_CONFLICT_KIND_CONTEXT: StudyConflictKind.ValueType  # 1
"""The run's context differs from the study's."""
STUDY_CONFLICT_KIND_CODE: StudyConflictKind.ValueType  # 2
"""The strategy's source differs from the one the study pinned."""
STUDY_CONFLICT_KIND_DUPLICATE_RUN: StudyConflictKind.ValueType  # 3
"""The study already holds a run with the same parameters."""
Global___StudyConflictKind: _TypeAlias = StudyConflictKind  # noqa: Y015

class _ErrorCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ErrorCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ERROR_CODE_UNSPECIFIED: _ErrorCode.ValueType  # 0
    ERROR_CODE_INVALID_MESSAGE: _ErrorCode.ValueType  # 1
    """The frame is not a ClientMessage, or its body is unset."""
    ERROR_CODE_INVALID_ARGUMENT: _ErrorCode.ValueType  # 2
    ERROR_CODE_NOT_FOUND: _ErrorCode.ValueType  # 3
    ERROR_CODE_UNIMPLEMENTED: _ErrorCode.ValueType  # 4
    """The server does not handle this body."""
    ERROR_CODE_UNSUPPORTED_VERSION: _ErrorCode.ValueType  # 5
    ERROR_CODE_INTERNAL: _ErrorCode.ValueType  # 6
    ERROR_CODE_RESOURCE_EXHAUSTED: _ErrorCode.ValueType  # 7
    """One indivisible response record exceeds the maximum envelope size."""

class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper): ...

ERROR_CODE_UNSPECIFIED: ErrorCode.ValueType  # 0
ERROR_CODE_INVALID_MESSAGE: ErrorCode.ValueType  # 1
"""The frame is not a ClientMessage, or its body is unset."""
ERROR_CODE_INVALID_ARGUMENT: ErrorCode.ValueType  # 2
ERROR_CODE_NOT_FOUND: ErrorCode.ValueType  # 3
ERROR_CODE_UNIMPLEMENTED: ErrorCode.ValueType  # 4
"""The server does not handle this body."""
ERROR_CODE_UNSUPPORTED_VERSION: ErrorCode.ValueType  # 5
ERROR_CODE_INTERNAL: ErrorCode.ValueType  # 6
ERROR_CODE_RESOURCE_EXHAUSTED: ErrorCode.ValueType  # 7
"""One indivisible response record exceeds the maximum envelope size."""
Global___ErrorCode: _TypeAlias = ErrorCode  # noqa: Y015

@_typing.final
class Error(_message.Message):
    """Lives here rather than in envelope.proto so that area files can embed it without an import cycle."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DetailsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    DETAILS_FIELD_NUMBER: _builtins.int
    STUDY_CONFLICT_FIELD_NUMBER: _builtins.int
    code: Global___ErrorCode.ValueType
    message: _builtins.str
    @_builtins.property
    def details(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def study_conflict(self) -> Global___StudyConflict: ...
    def __init__(
        self,
        *,
        code: Global___ErrorCode.ValueType = ...,
        message: _builtins.str = ...,
        details: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        study_conflict: Global___StudyConflict | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "study_conflict", b"study_conflict"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "detail", b"detail", "details", b"details", "message", b"message", "study_conflict", b"study_conflict"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_detail: _TypeAlias = _typing.Literal["study_conflict"]  # noqa: Y015
    _WhichOneofArgType_detail: _TypeAlias = _typing.Literal["detail", b"detail"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_detail) -> _WhichOneofReturnType_detail | None: ...

Global___Error: _TypeAlias = Error  # noqa: Y015

@_typing.final
class StudyConflict(_message.Message):
    """Why a run does not fit the study it names; the code is ERROR_CODE_INVALID_ARGUMENT."""

    DESCRIPTOR: _descriptor.Descriptor

    KIND_FIELD_NUMBER: _builtins.int
    CONTEXT_KEYS_FIELD_NUMBER: _builtins.int
    RUN_ID_FIELD_NUMBER: _builtins.int
    kind: Global___StudyConflictKind.ValueType
    run_id: _builtins.str
    """DUPLICATE_RUN only: the study's run with the same parameters."""
    @_builtins.property
    def context_keys(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """CONTEXT only: the context keys whose values differ from the study's."""

    def __init__(
        self,
        *,
        kind: Global___StudyConflictKind.ValueType = ...,
        context_keys: _abc.Iterable[_builtins.str] | None = ...,
        run_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_run_id", b"_run_id", "run_id", b"run_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_run_id", b"_run_id", "context_keys", b"context_keys", "kind", b"kind", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__run_id: _TypeAlias = _typing.Literal["run_id"]  # noqa: Y015
    _WhichOneofArgType__run_id: _TypeAlias = _typing.Literal["_run_id", b"_run_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__run_id) -> _WhichOneofReturnType__run_id | None: ...

Global___StudyConflict: _TypeAlias = StudyConflict  # noqa: Y015
